swagger: "2.0"
info:
  description: "To Do..."
  version: "1.0.0"
  title: "New Project"
host: "newproject.swagger.io"
basePath: "/v2"
tags:
  - name: "User"
  - name: "Product"
  - name: "Category"
  - name: "Order"
schemes:
  - "https"
  - "http"
paths:
  /users/{id}:
    get:
      tags:
        - "User"
      summary: "Find User by ID"
      description: "Returns a single User"
      operationId: "getUserById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of User to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "User Not Found"
      security:
        - api_key: []
    delete:
      tags:
        - "User"
      summary: "Deletes a User by Id"
      description: "Delete a user of the database"
      operationId: "deleteUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "User id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Deleted User"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "User not found"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
  /users:
    get:
      tags:
        - "User"
      summary: "Get All Users"
      description: "Return All User"
      operationId: "getUsers"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
      security:
        - api_key: []
    post:
      tags:
        - "User"
      summary: "Post New User"
      description: "Add new user to the database"
      operationId: "addUser"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be added to the Database."
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "405":
          description: "Invalid input user"
        "201":
          description: "Created new user"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
    put:
      tags:
        - "User"
      summary: "Update an existing User"
      description: "Updating an existing user's data"
      operationId: "updateUser"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be update to the database."
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "User Not Found"
        "200":
          description: "OK - Updated User"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
  /products/{id}:
    get:
      tags:
        - "Product"
      summary: "Get Products by ID"
      description: "Returns a single Product"
      operationId: "getUProductById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Product to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Product Not Found"
      security:
        - api_key: []
  /products:
    get:
      tags:
        - "Product"
      summary: "Get All Products"
      description: "Return All Products"
      operationId: "getProducts"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Product"
      security:
        - api_key: []
  /categories/{id}:
    get:
      tags:
        - "Category"
      summary: "Find Category by ID"
      description: "Returns a single Category"
      operationId: "getCategoryById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Category to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Category"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Category Not Found"
      security:
        - api_key: []
  /categories:
    get:
      tags:
        - "Category"
      summary: "Get All CAtegories"
      description: "Return All Categories"
      operationId: "getCategories"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Category"
      security:
        - api_key: []
  /orders/{id}:
    get:
      tags:
        - "Order"
      summary: "Find Order by ID"
      description: "Returns a single Order"
      operationId: "getOrderById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Order to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Order Not Found"
      security:
        - api_key: []
  /orders:
    get:
      tags:
        - "Order"
      summary: "Get All Orders"
      description: "Return All Orders"
      operationId: "getOrders"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Order"
      security:
        - api_key: []
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  User:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
  Category:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  Product:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      descriprion:
        type: "string"
      price:
        type: "number"
        format: "double"
      category:
        type: "string"
    xml:
      name: "Product"
  OrderItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nameProduct:
        type: "string"
      quantity:
        type: "integer"
      price:
        type: "number"
        format: "double"
      subTotal:
        type: "number"
        format: "double"
    xml:
      name: "OrderItem"
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      moment:
        type: "string"
        example: "2023-05-24T08:30:50"
      status:
        type: "string"
        description: "Order Status"
        enum:
          - "waiting payment"
          - "paid"
          - "shipped"
          - "delivered"
          - "canceled"
      orderItem:
        type: "array"
        items:
          $ref: "#/definitions/OrderItem"
    xml:
      name: "Order"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"