swagger: "2.0"
info:
  description: "To Do..."
  version: "1.0.0"
  title: "New Project"
host: "newproject.swagger.io"
basePath: "/v2"
tags:
  - name: "User"
  - name: "Product"
  - name: "Category"
  - name: "Order"
schemes:
  - "https"
  - "http"
paths:
  /user/{id}:
    get:
      tags:
        - "User"
      summary: "Get User"
      description: "Returns an User by Id"
      operationId: "getUserById"
      parameters:
        - name: "id"
          in: "path"
          description: "User Id to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "User Not Found"
    delete:
      tags:
        - "User"
      summary: "Deletes an User"
      description: "Delete an User by Id"
      operationId: "deleteUser"
      parameters:
        - name: "id"
          in: "path"
          description: "User id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Deleted User"
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "User not found"
    put:
      tags:
        - "User"
      summary: "Update User"
      description: "Updating an existing user's fields"
      operationId: "updateUser"
      parameters:
        - name: "id"
          in: "path"
          description: "User Id to updating"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "User's fields that needs to be update."
          required: true
          schema:
            $ref: "#/definitions/PutUserRequest"
      responses:
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "User Not Found"
        "200":
          description: "OK - Updated User"
  /users:
    get:
      tags:
        - "User"
      summary: "Get All Users"
      description: "Returns all User"
      operationId: "getUsers"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetUsersResponse"
    post:
      tags:
        - "User"
      summary: "Post New User"
      description: "Add new user"
      operationId: "addUser"
      parameters:
        - in: "body"
          name: "body"
          description: "User's field that needs to be post."
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "405":
          description: "Invalid input user"
        "201":
          description: "Created new user"
  /product/{id}:
    get:
      tags:
        - "Product"
      summary: "Get Product"
      description: "Get an product"
      operationId: "getUProductById"
      parameters:
        - name: "id"
          in: "path"
          description: "Product Id to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "Product Not Found"

    delete:
      tags:
        - "Product"
      summary: "Deletes an product"
      description: "Delete an existing Product"
      operationId: "deleteProduct"
      parameters:
        - name: "id"
          in: "path"
          description: "Product Id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Deleted Product"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Product not found"
    put:
      tags:
        - "Product"
      summary: "Update an Product"
      description: "Updating an existing Product's fields"
      operationId: "updateProduct"
      parameters:
        - name: "id"
          in: "path"
          description: "Product id to updating"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Product's fields that needs to be update."
          required: true
          schema:
            $ref: "#/definitions/PutProductRequest"
      responses:
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "Product Not Found"
        "200":
          description: "OK - Updated Product"
  /products:
    get:
      tags:
        - "Product"
      summary: "Get Products"
      description: "Return All Products"
      operationId: "getProducts"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/GetProductsResponse"
    post:
      tags:
        - "Product"
      summary: "Post product"
      description: "Add new product"
      operationId: "addProduct"
      parameters:
        - in: "body"
          name: "body"
          description: "Product's field that needs to be post."
          required: true
          schema:
            $ref: "#/definitions/PostProductRequest"
      responses:
        "405":
          description: "Invalid input product"
        "201":
          description: "Created new product"
  /category/{id}:
    get:
      tags:
        - "Category"
      summary: "Find Category by ID"
      description: "Returns a single Category"
      operationId: "getCategoryById"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Category to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Category"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Category Not Found"
    put:
      tags:
        - "Category"
      summary: "Update Category"
      description: "Updating an existing Category"
      operationId: "putCategoryById"
      parameters:
        - name: "id"
          in: "path"
          description: "Category id to updating"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Category's fields that needs to be update."
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        "400":
          description: "Invalid Id Supplied"
        "404":
          description: "Category Not Found"
        "200":
          description: "OK - Updated Category"
    delete:
      tags:
        - "Category"
      summary: "Deletes an category"
      description: "Delete an existing Product"
      operationId: "deleteCategory"
      parameters:
        - name: "id"
          in: "path"
          description: "Category Id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "204":
          description: "Deleted Category"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Category not found"
  /categories:
    get:
      tags:
        - "Category"
      summary: "Get All CAtegories"
      description: "Return All Categories"
      operationId: "getCategories"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/GetCategoriesResponse"
    post:
      tags:
        - "Category"
      summary: "Post Category"
      description: "Add new Category"
      operationId: "addCategory"
      parameters:
        - in: "body"
          name: "body"
          description: "Category's field that needs to be post."
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        "405":
          description: "Invalid input category"
        "201":
          description: "Created new category"
  /orders/{id}:
    get:
      tags:
        - "Order"
      summary: "Find Order by ID"
      description: "Returns a single Order"
      operationId: "getOrderById"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Order to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: "Invalid ID Supplied"
        "404":
          description: "Order Not Found"
  /orders:
    get:
      tags:
        - "Order"
      summary: "Get All Orders"
      description: "Return All Orders"
      operationId: "getOrders"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Order"
definitions:
  User:
    type: "object"
    required:
      - "name"
      - "phone"
      - "password"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
  GetUsersResponse:
    type: "array"
    items:
      $ref: "#/definitions/User"
  PutUserRequest:
    type: "object"
    required:
      - "name"
      - "email"
      - "phone"
      - "password"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
  Category:
    type: "object"
    required:
      - "name"
    properties:
      name:
        type: "string"
  GetCategoriesResponse:
    type: "array"
    items:
      $ref: "#/definitions/Category"
  Product:
    type: "object"
    required:
      - "name"
      - "price"
      - "category"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "double"
        example: "11.11"
      category:
        type: "string"
  PutProductRequest:
    type: "object"
    required:
      - "name"
      - "description"
      - "price"
      - "category"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "double"
        example: "11.11"
      category:
        type: "integer"
        format: "int64"
  PostProductRequest:
    type: "object"
    required:
      - "name"
      - "description"
      - "price"
      - "category"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "double"
        example: "11.11"
      category:
        type: "integer"
        format: "int64"
  GetProductsResponse:
    type: "array"
    items:
      $ref: "#/definitions/Product"
  OrderItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nameProduct:
        type: "string"
      quantity:
        type: "integer"
      price:
        type: "number"
        format: "double"
      subTotal:
        type: "number"
        format: "double"
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      moment:
        type: "string"
        example: "2023-05-24T08:30:50"
      status:
        type: "string"
        description: "Order Status"
        enum:
          - "waiting payment"
          - "paid"
          - "shipped"
          - "delivered"
          - "canceled"
      orderItem:
        type: "array"
        items:
          $ref: "#/definitions/OrderItem"